# Generated by Django 3.2.7 on 2022-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_artikel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='tumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/tumbnail'),
        ),
    ]
