# Generated by Django 3.2.7 on 2022-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_artikel_tumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='tumbnail',
        ),
        migrations.AddField(
            model_name='artikel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/thumbnail'),
        ),
    ]
